version: "3.8"

services:
  hono:
    container_name: hono
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      AUTH_SECRET: ${AUTH_SECRET}
    build:
      context: .
      dockerfile: ./apps/hono/Dockerfile
      args:
        POSTGRES_URL: ${POSTGRES_URL}
        AUTH_SECRET: ${AUTH_SECRET}
    restart: always
    ports:
      - 8787:8787
    networks:
      - app_network

  nextjs-pages:
    container_name: nextjs-pages
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      AUTH_SECRET: ${AUTH_SECRET}
    build:
      context: .
      dockerfile: ./apps/nextjs-pages/Dockerfile
      args:
        POSTGRES_URL: ${POSTGRES_URL}
        AUTH_SECRET: ${AUTH_SECRET}
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  bot:
    container_name: bot
    environment:
      BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
      args:
        BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
    restart: always
    ports:
      - 6969:6969
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
